Vagrant.configure("2") do |config|
  $script = <<-SCRIPT
  cd ~/folio-tools/api-doc
  yarn install
  pip install -r requirements.txt
  SCRIPT

  config.vm.define "testing" do |default|
    default.vm.box = "folio/testing"
    default.vm.network "private_network", ip: "192.168.56.101"
    default.vm.network "forwarded_port", guest: 3000, host: 3000, disabled: true
    default.vm.network "forwarded_port", guest: 3000, host: 3001
    default.vm.network "forwarded_port", guest: 5432, host: 5432
    default.vm.provider "virtualbox" do |v|
      v.memory = 20480
    end

    default.vm.provision "shell", inline: $script, privileged: false
  end

  config.vm.define "stock" do |stock|
    stock.vm.box = "folio/release"
    stock.vm.network "private_network", ip: "192.168.56.101"
    stock.vm.network "forwarded_port", guest: 3000, host: 3000, disabled: true
    stock.vm.network "forwarded_port", guest: 3000, host: 3001
    stock.vm.network "forwarded_port", guest: 5432, host: 5432
    stock.vm.provider "virtualbox" do |v|
      v.memory = 20480
    end

    stock.vm.provision "shell", inline: $script, privileged: false
  end
end
